controller_list:
  - name: fake_right_arm_controller
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
  - name: fake_left_arm_controller
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
  - name: fake_right_hand_controller
    joints:
      - RFinger11
      - RFinger12
      - RFinger13
      - RFinger21
      - RFinger22
      - RFinger23
      - RThumb1
      - RThumb2
  - name: fake_left_hand_controller
    joints:
      - LFinger11
      - LFinger12
      - LFinger13
      - LFinger21
      - LFinger22
      - LFinger23
      - LThumb1
      - LThumb2
  - name: fake_base_controller
    joints:
      - virtual_joint
